/* ACCOUNT */

export const ACCOUNT_SIGNIN = "ACCOUNT_SIGNIN";
export const ACCOUNT_SIGNIN_SUCCESS = "ACCOUNT_SIGNIN_SUCCESS";
export const ACCOUNT_SIGNIN_FAILURE = "ACCOUNT_SIGNIN_FAILURE";

export const ACCOUNT_SIGNUP = "ACCOUNT_SIGNUP";
export const ACCOUNT_SIGNUP_SUCCESS = "ACCOUNT_SIGNUP_SUCCESS";
export const ACCOUNT_SIGNUP_FAILURE = "ACCOUNT_SIGNUP_FAILURE";

export const ACCOUNT_GET_STATUS = "ACCOUNT_GET_STATUS";
export const ACCOUNT_GET_STATUS_SUCCESS = "ACCOUNT_GET_STATUS_SUCCESS";
export const ACCOUNT_GET_STATUS_FAILURE = "ACCOUNT_GET_STATUS_FAILURE";

export const ACCOUNT_SIGNOUT = "ACCOUNT_SIGNOUT";