/* ACCOUNT */

export const ACCOUNT_SIGNIN = "ACCOUNT_SIGNIN";
export const ACCOUNT_SIGNIN_SUCCESS = "ACCOUNT_SIGNIN_SUCCESS";
export const ACCOUNT_SIGNIN_FAILURE = "ACCOUNT_SIGNIN_FAILURE";

export const ACCOUNT_SIGNUP = "ACCOUNT_SIGNUP";
export const ACCOUNT_SIGNUP_SUCCESS = "ACCOUNT_SIGNUP_SUCCESS";
export const ACCOUNT_SIGNUP_FAILURE = "ACCOUNT_SIGNUP_FAILURE";

export const ACCOUNT_GET_STATUS = "ACCOUNT_GET_STATUS";
export const ACCOUNT_GET_STATUS_SUCCESS = "ACCOUNT_GET_STATUS_SUCCESS";
export const ACCOUNT_GET_STATUS_FAILURE = "ACCOUNT_GET_STATUS_FAILURE";

export const ACCOUNT_SIGNOUT = "ACCOUNT_SIGNOUT";

export const WORD_CHECK_PUT = "WORD_CHECK_PUT";
export const WORD_CHECK_PUT_SUCCESS = "WORD_CHECK_PUT_SUCCESS";
export const WORD_CHECK_PUT_FAILURE = "WORD_CHECK_PUT_FAILURE";

export const WORDBOOK_LIST = "WORDBOOK_LIST";
export const WORDBOOK_LIST_SUCCESS = "WORDBOOK_LIST_SUCCESS";
export const WORDBOOK_LIST_FAILURE = "WORDBOOK_LIST_FAILURE"